# Generated by Django 4.2.7 on 2025-07-02 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('productivity', 'Productivity'), ('time_management', 'Time Management'), ('priority_management', 'Priority Management'), ('workload_balance', 'Workload Balance'), ('improvement', 'Improvement Suggestion')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0)),
                ('impact_score', models.FloatField(default=0)),
                ('is_actionable', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'insight_type'], name='analytics_u_user_id_3c7e3a_idx'), models.Index(fields=['is_read', 'is_actionable'], name='analytics_u_is_read_afed92_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('average_completion_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductivityStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_type', models.CharField(choices=[('daily_completion', 'Daily Task Completion'), ('weekly_completion', 'Weekly Goal Achievement'), ('no_failures', 'No Failed Tasks'), ('high_efficiency', 'High Efficiency Days')], max_length=50)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField()),
                ('min_tasks_per_day', models.IntegerField(default=1)),
                ('min_completion_rate', models.FloatField(default=80.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'streak_type'], name='analytics_p_user_id_da58e0_idx')],
                'unique_together': {('user', 'streak_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('ongoing_tasks', models.IntegerField(default=0)),
                ('total_estimated_time', models.IntegerField(default=0)),
                ('total_actual_time', models.IntegerField(default=0)),
                ('average_completion_time', models.FloatField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('time_efficiency', models.FloatField(default=0)),
                ('high_priority_completed', models.IntegerField(default=0)),
                ('medium_priority_completed', models.IntegerField(default=0)),
                ('low_priority_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_p_user_id_7e7e2e_idx'), models.Index(fields=['date'], name='analytics_p_date_f57034_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_completion_rate', models.FloatField(help_text='Target completion rate as percentage')),
                ('target_daily_tasks', models.IntegerField(help_text='Target number of tasks per day')),
                ('target_weekly_tasks', models.IntegerField(help_text='Target number of tasks per week')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_completion_rate', models.FloatField(default=0)),
                ('current_daily_average', models.FloatField(default=0)),
                ('current_weekly_average', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='analytics_g_user_id_4fc43e_idx'), models.Index(fields=['end_date'], name='analytics_g_end_dat_aa7ed1_idx')],
            },
        ),
    ]
